dist: xenial
sudo: false
env:
  global:
  - REPO=SITEMAP_TXT
  - BAIDU_API="https://www.ixmu.net/sitemap.txt"
script:
- mkdir sitemap
- cd sitemap
- curl -s ${SITEMAP_TXT_URL}
- head -n 5 url.txt
- curl -H 'Content-Type:text/plain' --data-binary @url.txt ${BAIDU_API}
