name: push-urls-to-baidu
on:
  schedule:
    - cron: 40 8 * * *
  watch:
    types: started
jobs:
  push-urls-to-baidu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: push-urls-to-baidu
        env:
          sitemap_txt_url: ${{ secrets.sitemap_txt_url }}
          baidu_api: ${{ secrets.baidu_api }}
        run: |
          wget $sitemap_txt_url -qO urls.txt
          curl -s -H 'Content-Type:text/plain' --data-binary @urls.txt $baidu_api
